### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by elmarti** [a-cordier/wasm-audio#29]
Hey, great project! What's the license for this? 

I just want to fork and create a derivative

**Comment by a-cordier** [comment]
@elmarti sorry for the delay and thanks for the feedback, I'll try and add license headers this week-end. You can consider it as GPLv3

**Comment by elmarti** [comment]
@a-cordier thanks! I was just about to have another go at this!

**Comment by a-cordier** [comment]
Closing as license header has been added to all files.
